### ISSUE TITLE
Give admin access on repo to @patcon

### ISSUE THREAD

**Issue by patcon** [eduardomazevedo/eduardomazevedo.github.io#1]
If you'd rather not give admin, I believe I should be able to do this with push, so whichever you're comfortable with :)

Thanks!

**Comment by eduardomazevedo** [comment]
I added you as a collaborator. LMK if you need more permissions. thnks

**Comment by eduardomazevedo** [comment]
Hey, I just added you as a collaborator.

Eduardo Azevedo
Assistant Professor
The Wharton School
www.eduardoMazevedo.com
