### ISSUE TITLE
Give @patcon admin access to repo

### ISSUE THREAD

**Issue by patcon** [eduardomazevedo/eduardomazevedo.github.io#2]
Hey eduardo! Had a few hours to get the novel parts of the conversion done today. Work is in: https://github.com/patcon/eduardomazevedo.github.io/pull/1

In order to set up heroku review apps, I'll need more than push access on the repo. Happy to give it back to you after :)

**Comment by eduardomazevedo** [comment]
Hi Patrick. I saw the Heroku deployment on your fork. It will be neat to
have that when you do the bootstrap conversion.

Re admin access, I tried to give it to you, but I can't figure out where. I
google it, and it looks like personal repos only have owner and
collaborator access, so maybe that is the problem?
https://help.github.com/articles/permission-levels-
for-a-user-account-repository/#collaborator-access-on-a-
repository-owned-by-a-user-account

If you tell me how to give admin access I am happy to do it. Alternatively,
you can work on your fork and I will just move that to my repo when you are
done.

Eduardo Azevedo
Assistant Professor
The Wharton School
www.eduardoMazevedo.com
